# Generated by Django 3.2.8 on 2022-04-14 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('doc', models.CharField(max_length=120)),
                ('about', models.CharField(max_length=120)),
                ('active', models.BooleanField()),
                ('site', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('doc', models.CharField(max_length=120)),
                ('about', models.CharField(max_length=120)),
                ('active', models.BooleanField()),
                ('site', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('from_place', models.CharField(max_length=120)),
                ('initial_value', models.FloatField()),
                ('amount', models.FloatField()),
                ('amount_type', models.CharField(max_length=10)),
                ('id_cliente2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('amount', models.FloatField()),
                ('id_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.oferta')),
                ('id_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
